name: Tests

on: [push, pull_request]

jobs:
  linux-x86_64:
    name: "Linux x86_64 Machine Code Build"
    runs-on: ubuntu-latest   # this should force x86_64 when it becomes an option
    steps:
      - uses: actions/checkout@main
      - run: scripts/posix/build.sh --min
      - run: test/test-final.sh

  test-platform:
    name: "Linux Platform-Specific Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: test/test-platform.sh

  test-core:
    name: "Core Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: scripts/posix/build.sh --setup --dev
      - run: test/test-core.sh

  test-bootstrapped:
    name: "Bootstrapped Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: scripts/posix/build.sh --setup --dev
      - run: test/test-bootstrap.sh
