name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: scripts/posix/build.sh

      - name: Test core
        run: test/test-core.sh

      - name: Test core as bootstrapped
        run: test/test-bootstrap.sh

      - name: Test platform-specific
        run: test/test-platform.sh
